INSERT INTO "Stations" ("Name", "City", "Country")
VALUES ('Warszawa Centralna', 'Warsaw', 'Poland'),
       ('Kraków Główny', 'Kraków', 'Poland'),
       ('Gdańsk Główny', 'Gdańsk', 'Poland'),
       ('Wrocław Główny', 'Wrocław', 'Poland'),
       ('Poznań Główny', 'Poznań', 'Poland'),
       ('Łódź Fabryczna', 'Łódź', 'Poland'),
       ('Szczecin Główny', 'Szczecin', 'Poland'),
       ('Katowice', 'Katowice', 'Poland'),
       ('Lublin', 'Lublin', 'Poland'),
       ('Bydgoszcz Główna', 'Bydgoszcz', 'Poland'),
       ('Rzeszów Główny', 'Rzeszów', 'Poland'),
       ('Opole Główne', 'Opole', 'Poland'),
       ('Toruń Główny', 'Toruń', 'Poland'),
       ('Kielce', 'Kielce', 'Poland'),
       ('Białystok', 'Białystok', 'Poland'),
       ('Zielona Góra', 'Zielona Góra', 'Poland'),
       ('Gorzów Wlkp.', 'Gorzów Wlkp.', 'Poland'),
       ('Sosnowiec Główny', 'Sosnowiec', 'Poland'),
       ('Legnica', 'Legnica', 'Poland'),
       ('Elbląg', 'Elbląg', 'Poland'),
       ('Grudziądz', 'Grudziądz', 'Poland'),
       ('Jelenia Góra', 'Jelenia Góra', 'Poland'),
       ('Nowy Sącz', 'Nowy Sącz', 'Poland'),
       ('Tarnów', 'Tarnów', 'Poland'),
       ('Chorzów', 'Chorzów', 'Poland'),
       ('Dąbrowa Górnicza', 'Dąbrowa Górnicza', 'Poland'),
       ('Płock', 'Płock', 'Poland'),
       ('Świnoujście', 'Świnoujście', 'Poland'),
       ('Wałbrzych', 'Wałbrzych', 'Poland'),
       ('Częstochowa', 'Częstochowa', 'Poland'),
       ('Gniezno', 'Gniezno', 'Poland'),
       ('Kalisz', 'Kalisz', 'Poland'),
       ('Kutno', 'Kutno', 'Poland'),
       ('Kołobrzeg', 'Kołobrzeg', 'Poland'),
       ('Słupsk', 'Słupsk', 'Poland'),
       ('Piła', 'Piła', 'Poland'),
       ('Olsztyn', 'Olsztyn', 'Poland'),
       ('Pyrzyce', 'Pyrzyce', 'Poland'),
       ('Sandomierz', 'Sandomierz', 'Poland'),
       ('Włocławek', 'Włocławek', 'Poland'),
       ('Żory', 'Żory', 'Poland'),
       ('Sieradz', 'Sieradz', 'Poland'),
       ('Stargard', 'Stargard', 'Poland'),
       ('Chojnice', 'Chojnice', 'Poland'),
       ('Brzeg', 'Brzeg', 'Poland'),
       ('Głogów', 'Głogów', 'Poland'),
       ('Piekary Śląskie', 'Piekary Śląskie', 'Poland'),
       ('Zabrze', 'Zabrze', 'Poland'),
       ('Lędziny', 'Lędziny', 'Poland'),
       ('Jaworzno', 'Jaworzno', 'Poland'),
       ('Mysłowice', 'Mysłowice', 'Poland'),
       ('Łowicz', 'Łowicz', 'Poland'),
       ('Krotoszyn', 'Krotoszyn', 'Poland'),
       ('Nysa', 'Nysa', 'Poland'),
       ('Kędzierzyn-Koźle', 'Kędzierzyn-Koźle', 'Poland'),
       ('Lubliniec', 'Lubliniec', 'Poland'),
       ('Opole Lubelskie', 'Opole Lubelskie', 'Poland'),
       ('Węgierska Górka', 'Węgierska Górka', 'Poland'),
       ('Sanok', 'Sanok', 'Poland'),
       ('Głubczyce', 'Głubczyce', 'Poland'),
       ('Sieradz', 'Sieradz', 'Poland'),
       ('Gdynia Główna', 'Gdynia', 'Poland'),
       ('Włoszczowa', 'Włoszczowa', 'Poland'),
       ('Sławków', 'Sławków', 'Poland'),
       ('Braniewo', 'Braniewo', 'Poland'),
       ('Mińsk Mazowiecki', 'Mińsk Mazowiecki', 'Poland'),
       ('Mława', 'Mława', 'Poland'),
       ('Skarżysko-Kamienna', 'Skarżysko-Kamienna', 'Poland'),
       ('Tarnobrzeg', 'Tarnobrzeg', 'Poland'),
       ('Ząbkowice Śląskie', 'Ząbkowice Śląskie', 'Poland'),
       ('Głowno', 'Głowno', 'Poland'),
       ('Sędziszów Małopolski', 'Sędziszów Małopolski', 'Poland'),
       ('Białogard', 'Białogard', 'Poland'),
       ('Rypin', 'Rypin', 'Poland'),
       ('Sierpc', 'Sierpc', 'Poland'),
       ('Nowy Dwór Mazowiecki', 'Nowy Dwór Mazowiecki', 'Poland'),
       ('Kobyłka', 'Kobyłka', 'Poland'),
       ('Wadowice', 'Wadowice', 'Poland'),
       ('Słomniki', 'Słomniki', 'Poland'),
       ('Kraków Płaszów', 'Kraków', 'Poland'),
       ('Kościerzyna', 'Kościerzyna', 'Poland'),
       ('Przemyśl Główny', 'Przemyśl', 'Poland'),
       ('Włocławek Zazamcze', 'Włocławek', 'Poland'),
       ('Bielsko-Biała', 'Bielsko-Biała', 'Poland'),
       ('Piekary Śląskie', 'Piekary Śląskie', 'Poland'),
       ('Kobyłka', 'Kobyłka', 'Poland'),
       ('Skierniewice', 'Skierniewice', 'Poland'),
       ('Słomniki', 'Słomniki', 'Poland'),
       ('Radom', 'Radom', 'Poland'),
       ('Głogów', 'Głogów', 'Poland'),
       ('Kielce', 'Kielce', 'Poland'),
       ('Łódź Kaliska', 'Łódź', 'Poland'),
       ('Włocławek Zazamcze', 'Włocławek', 'Poland'),
       ('Stalowa Wola Rozwadów', 'Stalowa Wola', 'Poland'),
       ('Węgierska Górka', 'Węgierska Górka', 'Poland'),
       ('Gdańsk Stogi', 'Gdańsk', 'Poland'),
       ('Płock Borowicza', 'Płock', 'Poland'),
       ('Lublin Biskupa Jordana', 'Lublin', 'Poland'),
       ('Mława', 'Mława', 'Poland'),
       ('Łódź Radogoszcz', 'Łódź', 'Poland'),
       ('Sierpc', 'Sierpc', 'Poland'),
       ('Żory', 'Żory', 'Poland');